# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json

extends: default
rules:
  braces:
    forbid: non-empty
  brackets:
    forbid: non-empty
  comments-indentation: enable
  document-end:
    present: false
  document-start:
    present: false
  empty-lines:
    max: 1
  float-values:
    require-numeral-before-decimal: true
  indentation:
    spaces: 2
  key-duplicates: enable
  key-ordering: enable
  line-length:
    max: 10000
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
  quoted-strings:
    quote-type: double
    required: only-when-needed
  trailing-spaces: enable
  truthy: enable
