# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - kics --ci scan --path .
    image: docker.io/checkmarx/kics:v2.1.3-debian
    name: check-kics

when:
  - event: pull_request
