# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - markdownlint-cli2 **/*.md
    image: docker.io/davidanson/markdownlint-cli2:v0.14.0@sha256:9ae6011b3d978315ad283bf2af997ef08687a797b9e55086c94a90bf620f0783
    name: check-markdownlint-cli2

when:
  - event: pull_request
