# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - checkov -d .
    image: ghcr.io/bridgecrewio/checkov:3.2.258@sha256:116a68caaa959bc7ffd6d77d53f3d820ac4a80e1da7f3e02f477f23e5f37f65b
    name: check-checkov

when:
  - event: pull_request
