# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - apk add git
      - |
        git ls-tree --name-only -r HEAD | grep -E "^(.+\/)?.*[^\/\s]\.sh$" | while read f ; do
          echo "checking $f" && shfmt -d -s "$f"
        done
    image: docker.io/mvdan/shfmt:v3.9.0-alpine
    name: check-shfmt

when:
  - event: pull_request
