# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - checkov -d .
    image: ghcr.io/bridgecrewio/checkov:3.2.257@sha256:dceeed0d91273f734fbd2ae79593d1f2fe7b281080f4c2e0142cf90149cad826
    name: check-checkov

when:
  - event: pull_request
