# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - checkov -d .
    image: ghcr.io/bridgecrewio/checkov:3.2.260@sha256:a94155bdb982895b46bc45fd0070b63958f3d392bdbf5310779c711fae3105e8
    name: check-checkov

when:
  - event: pull_request
