# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - entrypoint:
      - /grype
      - dir:.
    environment:
      GRYPE_DB_CACHE_DIR: /cache/grype
    image: docker.io/anchore/grype:v0.82.1@sha256:9226c86d70e504976c645c42c02b4908bada3490b9ce20e56b46e3bf52155472
    name: check-grype
    volumes:
      - wp-cache_global_grype:/cache/grype

when:
  - event: pull_request
