# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - apk add git
      - |
        git ls-tree --name-only -r HEAD | grep -E "^(.+\/)?(.*[^\/\s]\.)?Dockerfile$" | while read f ; do
          echo "checking $f" && hadolint "$f"
        done
    image: docker.io/pipelinecomponents/hadolint:0.26.4
    name: check-hadolint

when:
  - event: pull_request
