# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - npm config --global set progress false
      - npm config --global set cache /cache/npm
      - npx "prettier@$PRETTIER_VERSION" --check .
    environment:
      # renovate: datasource=npm depName=prettier versioning=npm
      PRETTIER_VERSION: 3.3.3
    image: docker.io/library/node:23.0.0-bookworm@sha256:b9318f064e05337f029aab1b9056e63f264d51248f513613c79cf1c42829749b
    name: check-prettier
    volumes:
      - wp-cache_global_npm:/cache/npm

when:
  - event: pull_request
