jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          globs: "**.md"

name: lint-markdown

"on":
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/lint-markdown.yml
      - "**.md"
