name: lint-dockerfile

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: docker://docker.io/pipelinecomponents/hadolint:0.26.4
        with:
          entrypoint: sh
          args: -c 'find . -name 'Dockerfile' | while read f ; do hadolint "$f" ; done'

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/Dockerfile"
