jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: docker://docker.io/pipelinecomponents/hadolint:0.26.4
        with:
          args:
            - -c
            - find . -name "Dockerfile" | while read f ; do hadolint "$f" ; done
          entrypoint: sh

name: lint-dockerfile

"on":
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/lint-dockerfile.yml
      - "**/Dockerfile"
